local addother = ...
addother("Prison Life DrawTool",function()
	loadstring(game:HttpGet("https://raw.githubusercontent.com/SkidMaster999/RobloxScript/refs/heads/main/Game/PrisonLife/DrawTool.lua"))()
end)
addother("Infinite Yield",function()
	loadstring(game:HttpGet("https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source"))()
end)
addother("Nameless Admin (BEST)",function()
	loadstring(game:HttpGet("https://raw.githubusercontent.com/SkidMaster999/RobloxScriptArchive/refs/heads/main/NamelessAdmin.lua"))()
end)
addother("Walk On Walls",function()
	loadstring(game:HttpGet("https://pastebin.com/raw/RY9cBbdG"))()
end)
addother("FE Gui HUB",function()
	loadstring(game:HttpGet("https://pastebin.com/raw/VNtyMuFL"))()
end)
addother("Grab Knife",function()
	loadstring(game:HttpGet("https://rawscripts.net/raw/Prison-Life-Grab-Knife-works-on-prison-life-44287"))()
end)
addother("VStorm GUI",function()
	loadstring(game:HttpGet("https://rscripts.net/raw/prison-life-silent-aim-chat-bypasser-esp_1740318080798_GnonU3Zlwp.txt"))()
end)
addother("Etinity hub",function()
	loadstring(game:HttpGet("https://pastefy.app/UrQADv8R/raw?part=addon.lua"))()
end)
addother("Play Neckhurts Songs",function()
        loadstring(game:HttpGet("https://raw.githubusercontent.com/SkidMaster999/RobloxScript/refs/heads/main/Game/NeckerRadio.lua"))()
end)
addother("Test Script | Do Not Execute",function()
	loadstring(game:HttpGet("https://pastebin.com/raw/NbhZrjP4"))()
end)
